// examples/react/src/App.js
import React, { useRef, useEffect } from 'react';
import logo from './logo.svg';
import './App.css';

import '@vonage/video-publisher/video-publisher.js';
import '@vonage/video-subscribers/video-subscribers.js';

function App() {
  // Get references to Web Components
  const publisher = useRef(null);
  const subscribers = useRef(null);

  // These values normally come from the backend in a production application, but for this demo, they are hardcoded
  const applicationId = 'YOUR_APPLICATION_ID';
  const sessionId = 'YOUR_SESSION_ID';
  const token = 'YOUR_TOKEN';

  const toggleVideo = () => {
    publisher.current.toggleVideo();
  };

  const toggleAudio = () => {
    publisher.current.toggleAudio();
  };

  useEffect(() => {
    const OT = window.OT;

    // Initialize a Vonage Video Session object
    const session = OT.initSession(applicationId, sessionId);

    // Set session and token (and optionally properties) for Web Components
    publisher.current.session = session;
    publisher.current.token = token;
    publisher.current.properties = {
      fitMode: 'cover',
      height: '100%',
      resolution: '1920x1080',
      videoContentHint: 'detail',
      width: '100%',
    };
    subscribers.current.session = session;
    subscribers.current.token = token;
  });

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
      </header>
      <div className="App-container">
        <section className="App-section-publisher">
          <fieldset>
            <legend>Publisher</legend>
            <video-publisher ref={publisher}></video-publisher>
          </fieldset>
          <button onClick={toggleVideo}>
              toggle Video
          </button>
          <button onClick={toggleAudio}>
              toggle Audio
          </button>
        </section>
        <section className="App-section-subscribers">
          <fieldset>
            <legend>Subscribers</legend>
            <video-subscribers ref={subscribers}></video-subscribers>
          </fieldset>
        </section>
      </div>
    </div>
  );
}

export default App;

// examples/angular/src/app/app.component.ts
import {
  Component,
  VERSION,
  OnInit,
  AfterViewInit,
  ViewChild,
  ElementRef,
} from '@angular/core';
import '@vonage/video-publisher/video-publisher.js';
import '@vonage/video-subscribers/video-subscribers.js';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, AfterViewInit {
  name = 'Angular ' + VERSION.major;
  // These values normally come from a Video API backend SDK in a production application, but for this demo, they are hardcoded
  applicationId = 'YOUR_APPLICATION_ID';
  sessionId = 'YOUR_SESSION_ID';
  token = 'YOUR_TOKEN';
  // @ts-ignore
  OT = window.OT;
  session = {};
  pubProperties = {
    fitMode: 'cover',
    height: '100%',
    resolution: '1920x1080',
    videoContentHint: 'detail',
    width: '100%',
  };

  @ViewChild('publisher') publisherComponent: ElementRef;
  @ViewChild('subscribers') subscribersComponent: ElementRef;

  toggleVideo() {
    this.publisherComponent.nativeElement.toggleVideo();
  }

  toggleAudio() {
    this.publisherComponent.nativeElement.toggleAudio();
  }

  ngOnInit() {
    console.log('ngOnInit');
  }
  
  ngAfterViewInit() {
    // Initialize a Vonage Video Session object
    this.session = this.OT.initSession(this.applicationId, this.sessionId);
  }
  
}

<hello name="{{ name }}"></hello>
<p>Start editing to see some magic happen :)</p>
<div id="video-chat-container">
  <section id="publisher-container">
    <fieldset>
      <legend>Publisher</legend>
      <video-publisher #publisher [session]="session" [token]="token" [properties]="pubProperties"></video-publisher>
    </fieldset>
    <button type="button" (click)="toggleVideo()">toggle Video</button>
    <button type="button" (click)="toggleAudio()">toggle Audio</button>
  </section>
  <section id="subscribers-container">
    <fieldset>
      <legend>Subscribers</legend>
      <video-subscribers #subscribers [session]="session" [token]="token"></video-subscribers>
    </fieldset>
  </section>
</div>
