// examples/react/src/App.jsx
import React, { useRef, useEffect } from 'react';
import logo from './assets/react.svg';
import './App.css';

import '@vonage/video-publisher/video-publisher.js';
import '@vonage/video-subscribers/video-subscribers.js';

function App() {
  // Get references to Web Components
  const publisher = useRef(null);
  const subscribers = useRef(null);

  // If you have a Vonage Learning Server deployed, you can set your URL here.
  let serverURL;
  
  // OR you can hardcode the values here. (In production, you make a request to your backend to get these values.)
  const applicationId = 'YOUR_APPLICATION_ID';
  const sessionId = 'YOUR_SESSION_ID';
  const token = 'YOUR_TOKEN';

  function initializeSession() {
    // Initialize a Vonage Video Session object
    const session = OT.initSession(applicationId, sessionId);
  
    // Set session and token (and optionally properties) for Web Components
    publisher.current.session = session;
    publisher.current.token = token;
    publisher.current.properties = {
      fitMode: 'cover',
      height: '100%',
      resolution: '1920x1080',
      videoContentHint: 'detail',
      width: '100%',
    };
    subscribers.current.session = session;
    subscribers.current.token = token;    
  };

  const toggleVideo = () => {
    publisher.current.toggleVideo();
  };

  const toggleAudio = () => {
    publisher.current.toggleAudio();
  };

  useEffect(() => {
    const OT = window.OT;
    if (serverURL){
      const fetchCredentials = async () => {
        try {
          const response = await fetch(serverURL+ '/session');
          if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          const credentials = await response.json();
          applicationId = credentials.applicationId;
          sessionId = credentials.sessionId;
          token = credentials.token;
          initializeSession();
        } catch (err) {
          console.error('Error getting credentials: ', err.message);
        }
      };
      fetchCredentials();
    } else {
      initializeSession();
    };
  },[]);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
      </header>
      <div className="App-container">
        <section className="App-section-publisher">
          <fieldset>
            <legend>Publisher</legend>
            <video-publisher ref={publisher}></video-publisher>
          </fieldset>
          <button onClick={toggleVideo}>
              toggle Video
          </button>
          <button onClick={toggleAudio}>
              toggle Audio
          </button>
        </section>
        <section className="App-section-subscribers">
          <fieldset>
            <legend>Subscribers</legend>
            <video-subscribers ref={subscribers}></video-subscribers>
          </fieldset>
        </section>
      </div>
    </div>
  );
}

export default App;

// examples/svelte/src/App.svelte
<script>
  import { onMount, tick } from 'svelte';
  import svelteLogo from './assets/svelte.svg'
  import '@vonage/video-publisher/video-publisher.js';
  import '@vonage/video-subscribers/video-subscribers.js';

  let publisher;
  let subscribers;

  let serverURL;
  let applicationId = 'YOUR_APPLICATION_ID';
  let sessionId = 'YOUR_SESSION_ID';
  let token = 'YOUR_TOKEN';

  function initializeWebComponents(session) {
    // Set session and token (and optionally properties) for Web Components  
    if (publisher) {
      publisher.session = session;
      publisher.token = token;
      publisher.properties = {
        fitMode: 'cover',
        height: '100%',
        resolution: '1920x1080',
        videoContentHint: 'detail',
        width: '100%',
      };
    } else {
      console.log('Publisher Web Component reference is not available yet.');
    }
    if (subscribers) {
      subscribers.session = session;
      subscribers.token = token;
    } else {
      console.log('Subscribers Web Component reference is not available yet.');
    }
  }

  function initializeSession() {
    const session = OT.initSession(applicationId, sessionId);
    if (serverURL){
      initializeWebComponents(session);
    } else {
      $effect(() => {
        tick().then(() => {
          initializeWebComponents(session);
        });
      });
    }
  }

  function toggleVideo() {
    publisher.toggleVideo();
  }

  function toggleAudio() {
    publisher.toggleAudio();
  }

  onMount(() => {
    if (serverURL){
      const fetchCredentials = async () => {
        try {
          const response = await fetch(serverURL+ '/session');
          if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          const credentials = await response.json();
          applicationId = credentials.applicationId;
          sessionId = credentials.sessionId;
          token = credentials.token;
          initializeSession();
        } catch (err) {
          console.error('Error getting credentials: ', err.message);
        }
      };
      fetchCredentials();
    } else {
      initializeSession();
    };
	});
</script>

<header> 
  <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
</header>
<main id="video-chat-container">
  <section id="publisher-container">
    <fieldset>
      <legend>Publisher</legend>
      <video-publisher bind:this={publisher}></video-publisher>
    </fieldset>
    <button id="video-toggle"  on:click={toggleVideo}>toggle Video</button>
    <button id="audio-toggle"  on:click={toggleAudio}>toggle Audio</button>
  </section>
  <section id="subscribers-container">
    <fieldset>
      <legend>Subscribers</legend>
      <video-subscribers bind:this={subscribers}></video-subscribers>
    </fieldset>
  </section>
</main>

<style>
  #video-chat-container {
    display: flex;
    width: 100%;
  }

  #publisher-container {
    width: 400px;
  }

  #subscribers-container {
    width: 100%;
  }

  video-publisher {
    display: block;
    aspect-ratio: 16/9;
  }

  video-subscribers {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(360px, 1fr));
    place-items: center;
  }

  header {
    text-align: center;
    width: 100%;
  }
  
  img {
    height: 50px;
  }
</style>
